pipeline {
    agent any
    parameters {
        choice(name: 'NUMBER',
            choices: [10,20,30,40,50,60,70,80,90],
            description: 'Select the value for F(n) for the Fibonnai sequence.')
    }
    options {
        buildDiscarder(logRotator(daysToKeepStr: '10', numToKeepStr: '10'))
        timeout(time: 12, unit: 'HOURS')
        timestamps()
    }
    triggers {
        cron '@midnight'
    }
    stages {
        stage('Relative path') {
            steps {
                bat(".\\Ch03\\03_03-run-scripts-from-the-pipeline\\scripts\\fibonacci.bat ${params.NUMBER}")
            }
        } 
        stage('Full path') {
            steps {
                bat("${env.WORKSPACE}\\Ch03\\03_03-run-scripts-from-the-pipeline\\scripts\\fibonacci.bat ${params.NUMBER}")
            }
        }
        stage('Change directory') {
            steps {
                dir("${env.WORKSPACE}\\Ch03\\03_03-run-scripts-from-the-pipeline\\scripts"){
                    bat(".\\fibonacci.bat ${params.NUMBER}")
                }
            }
        }
    }
}
